name: Build Qt

on:
  workflow_call:
    inputs:
      build-windows:
        description: build windows
        type: boolean
        default: true
      build-linux:
        description: build linux
        type: boolean
        default: true
      build-macos:
        description: build macOS
        type: boolean
        default: true
      windows-runner:
        description: windows runner to use for amd64
        type: string
        default: windows-2025-vs2026
      version:
        description: qt version
        type: string
        required: true
      release:
        description: create a release
        type: boolean
        default: false
      submodules:
        description: submodules to use
        type: string
        required: false
      repo:
        description: release repository
        type: string
        default: crueter-ci/Qt

# TODO: Timestamp-based releases
env:
  CCACHE: "true"
  VERSION: ${{ inputs.version }}
  SUBMODULES: ${{ inputs.submodules }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

  UPLOAD_REPO: ${{ inputs.repo }}
  UPLOAD_RELEASE: ${{ inputs.release }}

jobs:
  download:
    name: Download
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6

      - name: Deps
        run: ./deps/source.sh

      - name: Download
        run: ./tools/download.sh

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: source
          path: qt-${{ env.VERSION }}.tar.zst
          archive: false

  windows:
    needs: [download]
    if: ${{ inputs.build-windows }}
    name: "${{ matrix.platform }} (${{ matrix.os.arch }})"
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - runs-on: ${{ inputs.windows-runner }}
            arch: amd64
            msystem: ucrt64

          - runs-on: windows-11-arm
            arch: arm64
            msystem: clangarm64
        platform: [windows, mingw]

    env:
      ARCH: ${{ matrix.os.arch }}
      PLATFORM: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v6

      - name: Install zstd and vulkan
        uses: crueter-ci/install-tools@master
        with:
          zstd: true
          vulkan: true

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ matrix.platform }}-${{ matrix.os.arch }}-${{ inputs.version }}-${{ inputs.repo }}
          restore-keys: ${{ matrix.platform }}-${{ matrix.os.arch }}-${{ inputs.version }}-${{ inputs.repo }}
          install: binary
          max-size: 2G

      - name: Setup MSVC
        uses: Eden-CI/msvc-dev-cmd@master
        if: matrix.platform == 'windows'
        with:
          arch: ${{ matrix.os.arch }}

      - uses: lukka/get-cmake@latest
        if: matrix.platform == 'windows'

      - name: Fix MSVC being stupid
        if: matrix.platform == 'windows' && matrix.os.arch == 'amd64' && inputs.windows-runner == 'windows-2025-vs2026'
        shell: cmd
        run: mklink /D "C:\Program Files\Microsoft Visual Studio\18\Community" "C:\Program Files\Microsoft Visual Studio\18\Enterprise"

      - name: Fix MSVC being stupid (arm)
        if: matrix.platform == 'windows' && (matrix.os.arch == 'arm64' || inputs.windows-runner != 'windows-2025-vs2026')
        shell: cmd
        run: mklink /D "C:\Program Files\Microsoft Visual Studio\2022\Community" "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"

      - name: Setup MSYS2 environment
        uses: msys2/setup-msys2@v2
        if: matrix.platform == 'mingw'
        with:
          msystem: ${{ matrix.os.msystem }}
          update: true
          install: >-
            git make unzip pkgconf diffutils patch
          pacboy: >-
            toolchain:p vulkan-devel:p pkg-config:p
            cmake:p ninja:p ccache:p libjpeg-turbo:p
            zlib:p libpng:p double-conversion:p
            freetype:p libtiff:p
          cache: false

      - name: Build
        uses: ./.github/workflows/build
        with:
          arch: ${{ matrix.os.arch }}
          platform: ${{ matrix.platform }}
          label: ${{ matrix.platform }}
          shell: ${{ matrix.platform == 'mingw' && 'msys2 {0}' || 'bash' }}

  arch:
    needs: [download]
    if: ${{ inputs.build-linux }}
    name: "Arch Linux (${{ matrix.arch }})"
    runs-on: ${{ matrix.runs-on }}
    container: ghcr.io/pkgforge-dev/archlinux:latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-latest
            arch: amd64

          - runs-on: ubuntu-24.04-arm
            arch: aarch64

    env:
      ARCH: ${{ matrix.arch }}
      PLATFORM: linux
      PACKAGE: true

    steps:
      - uses: actions/checkout@v6

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@main
        with:
          key: archlinux-${{ env.ARCH }}-${{ inputs.version }}-${{ inputs.repo }}
          restore-keys: archlinux-${{ env.ARCH }}-${{ inputs.version }}-${{ inputs.repo }}
          max-size: 2G
          update-package-index: true
          install: binary

      - name: Deps
        run: ./deps/arch.sh

      - name: Build
        uses: ./.github/workflows/build
        with:
          arch: ${{ matrix.arch }}
          platform: linux
          label: archlinux

  linux:
    needs: [download]
    if: ${{ inputs.build-linux }}
    name: "Linux (${{ matrix.arch }})"
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-latest
            arch: amd64

          - runs-on: ubuntu-24.04-arm
            arch: aarch64

    env:
      ARCH: ${{ matrix.arch }}
      PLATFORM: linux

    steps:
      - uses: actions/checkout@v6

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ env.PLATFORM }}-${{ env.ARCH }}-${{ inputs.version }}-${{ inputs.repo }}
          restore-keys: ${{ env.PLATFORM }}-${{ env.ARCH }}-${{ inputs.version }}-${{ inputs.repo }}
          max-size: 2G
          install: binary

      - name: Deps
        run: ./deps/linux.sh

      - name: Build
        uses: ./.github/workflows/build
        with:
          arch: ${{ matrix.arch }}
          platform: linux
          label: linux

  macos:
    needs: [download]
    if: ${{ inputs.build-macos }}
    name: "macOS (universal)"
    runs-on: macos-latest
    strategy:
      fail-fast: false

    env:
      ARCH: universal
      PLATFORM: macos

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ env.PLATFORM }}-${{ env.ARCH }}-${{ inputs.version }}-${{ inputs.repo }}
          restore-keys: ${{ env.PLATFORM }}-${{ env.ARCH }}-${{ inputs.version }}-${{ inputs.repo }}
          install: binary
          max-size: 2G

      - name: Deps
        run: ./deps/macos.sh

      - name: Build
        uses: ./.github/workflows/build
        with:
          arch: universal
          platform: macos
          label: macos

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [windows, arch, linux, macos]

    if: always() && inputs.release && !cancelled() && !failure()

    steps:
      - uses: actions/checkout@v6

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts
          pattern: '*-${{ inputs.version }}'
          merge-multiple: true

      - name: Generate Changelog
        run: ./tools/changelog.sh > changelog.md

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          body_path: ./changelog.md
          name: Qt ${{ inputs.version }}
          tag_name: v${{ inputs.version }}

  fake-release:
    name: Fake Release
    runs-on: ubuntu-latest
    needs: [windows, arch, linux, macos]

    if: always() && !inputs.release && !cancelled() && !failure()

    steps:
      - uses: actions/checkout@v6

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts
          pattern: '*-${{ inputs.version }}'
          merge-multiple: true

      - name: Generate Changelog
        run: ./tools/changelog.sh > changelog.md

      - name: Test
        run: |
          echo "Version: $VERSION"
          echo
          cat changelog.md

      - name: Check artifacts
        run:
          find artifacts -name "*.tar.zst*"