name: Eden (Widgets)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  qt-6-7-3:
    name: Qt 6.7.3
    uses: ./.github/workflows/platforms.yml
    secrets: inherit
    with:
      build-windows: false
      build-linux: false
      build-ios: false
      version: 6.7.3
      release: true
      submodules: qtbase,qttools,qtcharts
      repo: Eden-CI/Qt

  qt-6-11-1:
    name: Qt 6.11.1
    uses: ./.github/workflows/platforms.yml
    secrets: inherit
    with:
      version: 6.11.1
      release: true
      submodules: qtbase,qttools,qtcharts
      repo: Eden-CI/Qt
