name: QDash

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # qt-6-7-3:
  #   name: Qt 6.7.3
  #   uses: ./.github/workflows/platforms.yml
  #   with:
  #     build-windows: false
  #     build-linux: false
  #     build-macos: true
  #     version: 6.7.3
  #     release: true

  qt-6-11-1:
    name: Qt 6.11.1
    uses: ./.github/workflows/platforms.yml
    secrets: inherit
    with:
      version: 6.11.1
      release: true
      repo: QDash-CI/Qt
      submodules: qtbase,qtdeclarative,qtmultimedia

  # qt-6-10-2:
  #   name: Qt 6.10.2
  #   uses: ./.github/workflows/platforms.yml
  #   with:
  #     build-windows: true
  #     build-linux: true
  #     build-macos: true
  #     windows-runner: windows-2025-vs2026
  #     version: 6.10.2
  #     release: true
