name: Test Build

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
  qt-6-7-3:
    name: Qt 6.7.3
    uses: ./.github/workflows/platforms.yml
    with:
      build-windows: false
      build-linux: false
      build-ios: false
      version: 6.7.3
      release: false
      submodules: qtbase

  qt-6-11-1:
    name: Qt 6.11.0
    uses: ./.github/workflows/platforms.yml
    with:
      version: 6.11.1
      release: false
      submodules: qtbase,qttools
