name: Test Build

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
  qt-6-11-1:
    name: Qt 6.11.0
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      build-windows: true
      build-linux: true
      build-macos: true
      version: 6.11.1
      release: false
      submodules: qtbase,qttools
